/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class birc_grni_en_CommonFunction */

#ifndef _Included_birc_grni_en_CommonFunction
#define _Included_birc_grni_en_CommonFunction
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     birc_grni_en_CommonFunction
 * Method:    elnet
 * Signature: (F[FII[F[I[FIIIF[FFI[FILbirc/grni/en/ElnetResult;)V
 */
JNIEXPORT void JNICALL Java_birc_grni_en_CommonFunction_elnet
  (JNIEnv *, jclass, jfloat, jfloatArray, jint, jint, jfloatArray, jintArray, jfloatArray, jint, jint, jint, jfloat, jfloatArray, jfloat, jint, jfloatArray, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
