/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class birc_grni_rf_Genie3SingleTime */

#ifndef _Included_birc_grni_rf_Genie3SingleTime
#define _Included_birc_grni_rf_Genie3SingleTime
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     birc_grni_rf_Genie3SingleTime
 * Method:    rtenslearncless
 * Signature: (II[FI[FI[II[DLbirc/grni/rf/RtEnsParam;ILbirc/grni/rf/Plhs_Genie3SingleTime_Rtenslearncless;)V
 */
JNIEXPORT void JNICALL Java_birc_grni_rf_Genie3SingleTime_rtenslearncless
  (JNIEnv *, jclass, jint, jint, jfloatArray, jint, jfloatArray, jint, jintArray, jint, jdoubleArray, jobject, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
