/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class birc_grni_en_ElasticNet */

#ifndef _Included_birc_grni_en_ElasticNet
#define _Included_birc_grni_en_ElasticNet
#ifdef __cplusplus
extern "C" {
#endif
#undef birc_grni_en_ElasticNet_MAX_WORKER_THREADS
#define birc_grni_en_ElasticNet_MAX_WORKER_THREADS 10L
/*
 * Class:     birc_grni_en_ElasticNet
 * Method:    elnet
 * Signature: (F[FII[F[I[FIIIF[FFI[FILbirc/grni/en/ElnetResult;)V
 */
JNIEXPORT void JNICALL Java_birc_grni_en_ElasticNet_elnet
  (JNIEnv *, jclass, jfloat, jfloatArray, jint, jint, jfloatArray, jintArray, jfloatArray, jint, jint, jint, jfloat, jfloatArray, jfloat, jint, jfloatArray, jint, jobject);

#ifdef __cplusplus
}
#endif
#endif
